Eda İpek Sanlı 20040101006 Bilgisayar Mühendisliği

Kosinüs benzerliği: Cosine similarity, iki vektörün benzerliğini ölçmek için kullanılan bir metriktir. Özellikle, vektörlerin yön veya yönelim benzerliğini ölçerken büyüklük veya ölçek farklılıklarını göz ardı eder. Her iki vektör de aynı iç çarpım(dot product) uzayının bir parçası olmalıdır, yani iç çarpım çarpımıyla bir skalar üretmelidirler. İki vektörün benzerliği, aralarındaki açının kosinüsü ile ölçülür. Doğal dil işleme (NLP), öneri sistemleri, görüntü işleme, kümeleme gibi alanlarda kullanılır. Hesaplanması: 
similarity(A,B)= cosQ = A . B / ||A|| ||B||

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

corpus = [  'data science is one of the most important fields of science',
            'this is one of the best data science courses',
            'data scientists analyze data'   ]

# Create a matrix to represent the corpus
X = CountVectorizer().fit_transform(corpus).toarray()
print(X, "\n")

cos_sim_1_2 = cosine_similarity([X[0, :], X[1, :]])

print('Cosine Similarity between Document 1 and Document 2 is \n',cos_sim_1_2 )

[[0 0 0 1 1 1 1 1 2 1 2 0 1 0]
 [0 1 1 1 0 0 1 0 1 1 1 0 1 1]
 [1 0 0 2 0 0 0 0 0 0 0 1 0 0]] 

Cosine Similarity between Document 1 and Document 2 is 
 [[1.         0.68853037]
 [0.68853037 1.        ]]


Öklidyen uzaklık: Öklid mesafesi basitçe iki nokta arasındaki mesafedir. Noktalar bir düzlemdeyse, bu iki noktayı birleştiren doğru parçasının mesafesidir. Bu mesafe Pisagor teoremine göre hesaplanır.Kümeleme analizinde en çok kullanılan algoritmalardan biridir. Makine öğreniminde K-Nearest Neighbors (K-NN) gibi çeşitli algoritmalarda, K-Means gibi kümeleme yöntemlerinde ve özellik uzayındaki veri noktaları arasındaki benzerliğin değerlendirilmesinde sıklıkla kullanılır. Özellik temsillerine dayalı olarak örnekler arasındaki yakınlığın veya farklılığın belirlenmesine yardımcı olur.

In [8]:
import numpy as np

# Define two points as arrays or lists
point1 = np.array([2, 3])
point2 = np.array([5, 7])

# Calculate Euclidean distance between the points
euclidean_distance = np.linalg.norm(point1 - point2)

# Print the result
print("Euclidean Distance between point1 and point2:", euclidean_distance)

Euclidean Distance between point1 and point2: 5.0
